### ISSUE TITLE
Handling of empty layouts

### ISSUE THREAD

**Issue by kvark** [zakarumych/gpu-descriptor#14]
See https://github.com/gfx-rs/wgpu/issues/1390#issuecomment-842404932
Is this supposed to be handled by this library?

**Comment by zakarumych** [comment]
Descriptor set layouts with zero bindings are valid.

**Comment by kvark** [comment]
So this is a bug in gpu-descriptor then?

**Comment by almarklein** [comment]
To be precise, not sure if it matters, but the observed crash happens when a bind group with zero entries is created (in `wgpuDeviceCreateBindGroup`).

**Comment by zakarumych** [comment]
I see where problem comes from. While it is valid to create descriptor set layout with no descriptors, it is invalid to create descriptor pool with no descriptors. Which is weird. Why not allow or forbid both.
As a workaround, `gpu-descriptor` may add one dummy descriptor to the pool which won't be used.

**Comment by zakarumych** [comment]
Probably `DescriptorDevice` implementation may do so, as it is a Vulkan quirk.

**Comment by zakarumych** [comment]
Conceptually `DescriptorDevice` may return dummy pool which will be used to allocate dummy descriptor sets with no actual resources inside. But empty layout is kinda edge case, so supporting it somehow without affecting common use case is preferable.

**Comment by kvark** [comment]
Well that was quick. Thank you!

**Comment by zakarumych** [comment]
IIRC wgpu rolls its own `DescriptorDevice` for some reason. Same change should be applied there then

**Comment by kvark** [comment]
It's supposed to be just a glue between gpu-descriptor and gfx-hal. If gpu-descriptor doesn't consider this in scope, then we'd move it into the glue. But I think it's better to have gpu-descriptor handling this.

**Comment by zakarumych** [comment]
I think it's better to have Vulkan specific problem be handled in Vulkan API glue. gpu-descriptor will treat allocated pool as empty after all.
Maybe right in gfx-backend-vulkan?

**Comment by kvark** [comment]
This crate - gpu-descriptor - is supposed to be compatible with all the Vulkan users, right? So Ash, Erupt, gfx, and others potentially. So the problem affects everybody. If we put a fix in the glue, or into gfx-backend-vulkan, it's going to be fine for us. But it means that all the other clients will have to put in similar fixes. That doesn't sound good, comparing to a single place that address everything - right here.

**Comment by zakarumych** [comment]
You are correct. But how about other APIs? I suppose there's no such problem in gfx-backend-dx12 and metal.

**Comment by zakarumych** [comment]
I guess it is not big deal, giving that empty layout is degenerate case anyway.

**Comment by kvark** [comment]
On gfx-rs side, other APIs don't care about this. So we could indeed put it into gfx-backend-vulkan, but then all the other users of gpu-descriptor would have to do the same.

**Comment by zakarumych** [comment]
Ok. This sounds convincing enough. I'll put workaround into gpu-descriptor.
