### ISSUE TITLE
Purpose of this crate?

### ISSUE THREAD

**Issue by kvark** [zakarumych/gpu-descriptor#2]
Looking at the API, it has a notion of descriptor pools. Users are expected to create a descriptor pool with certain capacity, and then allocate/free descriptors from that pool. How does it help versus just using gfx-hal directly?
My expectation was that this crate would abstract away the management of descriptor pools , but it's not doing that. Compare to gfx-descriptor (and rendy-descriptor): https://docs.rs/gfx-descriptor/0.2.0/gfx_descriptor/struct.DescriptorAllocator.html

**Comment by zakarumych** [comment]
The notion of descriptor pools is for backend side of the API.
End-user simply creates `DescriptorAllocator` and uses it to allocate `DescriptorSet`s.

**Comment by zakarumych** [comment]
I guess you did `cargo doc --open` in crate root. By default it opens `gpu-descriptor-types` crate which contains core types and traits for backend to implement. See `gpu-descriptor`

**Comment by kvark** [comment]
I see now, thank you! Was missing `DescriptorAllocator`.
