### ISSUE TITLE
Release with new version of `hashbrown`, again

### ISSUE THREAD

**Issue by OvermindDL1** [zakarumych/gpu-descriptor#36]
As in https://github.com/zakarumych/gpu-descriptor/issues/24 there is another new hashbrown (that is causing multiple other old things to be brought in as well), can another patch release be done and released with modern hashbrown?

**Comment by atlv24** [comment]
Can we have the hashbrown dependency only present in no-std contexts please?

**Comment by zakarumych** [comment]
> Can we have the hashbrown dependency only present in no-std contexts please?

Why? Simply to have one less dependency?

**Comment by zakarumych** [comment]
@atlv24 if you know how to *disable* optional dependency when feature is *enabled* - PR is welcome.
But don't use default `std`'s hasher, it's too much.

**Comment by zakarumych** [comment]
I've released new version that uses latest hashbrown
